//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FFC_PDM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FFC_PDM.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;datetime&quot;,&quot;machineID&quot;,&quot;errorID&quot;
        ///2015-01-03 07:00:00,1,&quot;error1&quot;
        ///2015-01-03 20:00:00,1,&quot;error3&quot;
        ///2015-01-04 06:00:00,1,&quot;error5&quot;
        ///2015-01-10 15:00:00,1,&quot;error4&quot;
        ///2015-01-22 10:00:00,1,&quot;error4&quot;
        ///2015-01-25 15:00:00,1,&quot;error4&quot;
        ///2015-01-27 04:00:00,1,&quot;error1&quot;
        ///2015-03-03 22:00:00,1,&quot;error2&quot;
        ///2015-03-05 06:00:00,1,&quot;error1&quot;
        ///2015-03-20 18:00:00,1,&quot;error1&quot;
        ///2015-03-26 01:00:00,1,&quot;error2&quot;
        ///2015-03-31 23:00:00,1,&quot;error1&quot;
        ///2015-04-19 06:00:00,1,&quot;error2&quot;
        ///2015-04-19 06:00:00,1,&quot;error3&quot;
        ///2015-04-29 19:00:00,1,&quot;error4&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PdM_errors {
            get {
                return ResourceManager.GetString("PdM_errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;datetime&quot;,&quot;machineID&quot;,&quot;failure&quot;
        ///2015-01-05 06:00:00,1,&quot;comp4&quot;
        ///2015-03-06 06:00:00,1,&quot;comp1&quot;
        ///2015-04-20 06:00:00,1,&quot;comp2&quot;
        ///2015-06-19 06:00:00,1,&quot;comp4&quot;
        ///2015-09-02 06:00:00,1,&quot;comp4&quot;
        ///2015-10-17 06:00:00,1,&quot;comp2&quot;
        ///2015-12-16 06:00:00,1,&quot;comp4&quot;
        ///2015-03-19 06:00:00,2,&quot;comp1&quot;
        ///2015-03-19 06:00:00,2,&quot;comp2&quot;
        ///2015-04-18 06:00:00,2,&quot;comp2&quot;
        ///2015-12-29 06:00:00,2,&quot;comp2&quot;
        ///2015-01-07 06:00:00,3,&quot;comp2&quot;
        ///2015-02-06 06:00:00,3,&quot;comp1&quot;
        ///2015-07-21 06:00:00,3,&quot;comp2&quot;
        ///2015-10-04 06:00:00,3,&quot;comp2&quot;
        ///2015-12-03 06 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PdM_failures {
            get {
                return ResourceManager.GetString("PdM_failures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;machineID&quot;,&quot;model&quot;,&quot;age&quot;
        ///1,&quot;model3&quot;,18
        ///2,&quot;model4&quot;,7
        ///3,&quot;model3&quot;,8
        ///4,&quot;model3&quot;,7
        ///5,&quot;model3&quot;,2
        ///6,&quot;model3&quot;,7
        ///7,&quot;model3&quot;,20
        ///8,&quot;model3&quot;,16
        ///9,&quot;model4&quot;,7
        ///10,&quot;model3&quot;,10
        ///11,&quot;model2&quot;,6
        ///12,&quot;model3&quot;,9
        ///13,&quot;model1&quot;,15
        ///14,&quot;model3&quot;,1
        ///15,&quot;model3&quot;,14
        ///16,&quot;model1&quot;,3
        ///17,&quot;model1&quot;,14
        ///18,&quot;model3&quot;,15
        ///19,&quot;model3&quot;,17
        ///20,&quot;model2&quot;,16
        ///21,&quot;model2&quot;,14
        ///22,&quot;model1&quot;,14
        ///23,&quot;model1&quot;,17
        ///24,&quot;model1&quot;,20
        ///25,&quot;model4&quot;,16
        ///26,&quot;model3&quot;,3
        ///27,&quot;model3&quot;,9
        ///28,&quot;model4&quot;,1
        ///29,&quot;model4&quot;,3
        ///30,&quot;model3&quot;,20
        ///31,&quot;model1&quot;,11
        ///32,&quot;model4&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PdM_machines {
            get {
                return ResourceManager.GetString("PdM_machines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;datetime&quot;,&quot;machineID&quot;,&quot;comp&quot;
        ///2014-06-01 06:00:00,1,&quot;comp2&quot;
        ///2014-07-16 06:00:00,1,&quot;comp4&quot;
        ///2014-07-31 06:00:00,1,&quot;comp3&quot;
        ///2014-12-13 06:00:00,1,&quot;comp1&quot;
        ///2015-01-05 06:00:00,1,&quot;comp4&quot;
        ///2015-01-05 06:00:00,1,&quot;comp1&quot;
        ///2015-01-20 06:00:00,1,&quot;comp3&quot;
        ///2015-01-20 06:00:00,1,&quot;comp1&quot;
        ///2015-02-04 06:00:00,1,&quot;comp4&quot;
        ///2015-02-04 06:00:00,1,&quot;comp3&quot;
        ///2015-02-19 06:00:00,1,&quot;comp3&quot;
        ///2015-03-06 06:00:00,1,&quot;comp1&quot;
        ///2015-03-21 06:00:00,1,&quot;comp1&quot;
        ///2015-04-05 06:00:00,1,&quot;comp3&quot;
        ///2015-04-20 06:00:00,1,&quot;comp2&quot;
        ///2015-05-05 06:00 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PdM_maint {
            get {
                return ResourceManager.GetString("PdM_maint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to machineID,volt,rotate,pressure,vibration
        ///1,176.217853,418.5040782,113.0779355,45.08768576
        ///2,176.5589132,424.6241621,76.00533247,43.76704852
        ///3,185.4820432,461.2111374,87.45319939,28.21686425
        ///4,169.7108469,463.6467269,95.92987658,38.40037192
        ///5,165.0828994,452.2835762,84.5917221,40.29880253
        ///6,136.8785885,492.0884196,149.003582,22.97328948
        ///7,156.0063913,519.4979051,105.878295,42.52224477
        ///8,159.3793197,409.4192167,111.7357327,44.10403835
        ///1,162.8792229,402.7474896,95.46052538,43.41397268
        ///2,158.2820441,4 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PdM_PLC__edit {
            get {
                return ResourceManager.GetString("PdM_PLC__edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;datetime&quot;,&quot;machineID&quot;,&quot;volt&quot;,&quot;rotate&quot;,&quot;pressure&quot;,&quot;vibration&quot;
        ///2015-01-01 06:00:00,1,176.217853015625,418.504078221616,113.077935462083,45.0876857639276
        ///2015-01-01 07:00:00,1,162.87922289706,402.747489565395,95.4605253823187,43.4139726834815
        ///2015-01-01 08:00:00,1,170.989902405567,527.349825452291,75.2379048586662,34.1788471214451
        ///2015-01-01 09:00:00,1,162.462833264092,346.149335043074,109.248561276504,41.1221440884256
        ///2015-01-01 10:00:00,1,157.61002119306,435.376873016938,111.886648210168,25.99051099820 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PdM_telemetry {
            get {
                return ResourceManager.GetString("PdM_telemetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volt,rotate,pressure,vibration,errorID,model,age
        ///191.8731711,382.7366256,100.8936911,37.94021952,0,1,18
        ///182.021908,392.2701871,99.94629329,41.67618411,0,2,7
        ///164.9064664,410.7420748,91.72159297,35.4769705,0,3,8
        ///149.4096957,522.1231175,112.6804986,45.63786969,0,4,7
        ///178.7891968,415.1672978,142.4142734,47.02021034,0,5,2
        ///181.2091761,393.8531968,98.74357764,41.87911972,0,6,7
        ///181.3431133,339.7718811,107.4882337,37.93320846,0,7,20
        ///168.4391841,438.340305,89.90414074,32.15452413,0,8,16
        ///176.0074799,414.778969 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PdM_telemetry_latest {
            get {
                return ResourceManager.GetString("PdM_telemetry_latest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datetime,machineID,volt,rotate,pressure,vibration
        ///2015-01-01 6:00,1,176.217853,418.5040782,113.0779355,45.08768576
        ///2015-01-01 7:00,1,162.8792229,402.7474896,95.46052538,43.41397268
        ///2015-01-01 8:00,1,170.9899024,527.3498255,75.23790486,34.17884712
        ///2015-01-01 9:00,1,162.4628333,346.149335,109.2485613,41.12214409
        ///2015-01-01 10:00,1,157.6100212,435.376873,111.8866482,25.990511
        ///2015-01-01 11:00,1,172.5048392,430.3233621,95.92704169,35.65501733
        ///2015-01-01 12:00,1,156.5560306,499.0716231,111.7556843,42.7539 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PdM_telemetry_no_duplicates {
            get {
                return ResourceManager.GetString("PdM_telemetry_no_duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datetime,machineID,volt,rotate,pressure,vibration
        ///2015-01-01 6:00,1,176.217853,418.5040782,113.0779355,45.08768576
        ///2015-01-01 7:00,1,162.8792229,402.7474896,95.46052538,43.41397268
        ///2015-01-01 8:00,1,170.9899024,527.3498255,75.23790486,34.17884712
        ///2015-01-01 9:00,1,162.4628333,346.149335,109.2485613,41.12214409
        ///2015-01-01 10:00,1,157.6100212,435.376873,111.8866482,25.990511
        ///2015-01-01 11:00,1,172.5048392,430.3233621,95.92704169,35.65501733
        ///2015-01-01 12:00,1,156.5560306,499.0716231,111.7556843,42.7539 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PdM_telemetry_no_duplicates_cleaned {
            get {
                return ResourceManager.GetString("PdM_telemetry_no_duplicates_cleaned", resourceCulture);
            }
        }
    }
}
